FROM httpd:2.4-alpine

COPY scripts/init-htpasswd-prod.sh /scripts/init-htpasswd-prod.sh
COPY scripts/init-htpasswd-local.sh /scripts/init-htpasswd-local.sh
COPY nginx/htpasswd-local /defaults/htpasswd-local
RUN chmod +x /scripts/init-htpasswd-prod.sh /scripts/init-htpasswd-local.sh
