name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATA_API_TOKEN: ${{ secrets.EODHD_API_TOKEN }}
      PYTHONPATH: src
      AIRFLOW_ADMIN_USER: ${{ secrets.AIRFLOW_ADMIN_USER }}
      AIRFLOW_ADMIN_PASSWORD: ${{ secrets.AIRFLOW_ADMIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: Install just
        run: |
          curl -sL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Validate Python version match
        run: ./scripts/validate_python_version.sh

      - name: Install project dependencies
        run: just install-dev

      - name: Run format + type checks no fixes
        run: just lint-ci

      - name: Run tests
        run: just test

      - name: Generate structure.md
        run: just generate-structure-doc

      - name: Check for uncommitted changes in structure.md
        run: |
          git diff --exit-code docs/structure.md || (
            echo "::error::docs/structure.md is out of sync. Run 'just generate-structure-doc'."
            exit 1
          )

  docker:
    name: Build Docker Images
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install just
        run: |
          curl -sL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Generate .env from .python-version
        run: just docker-build
