name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src
      # Set optional tokens, if not exist, defaults to empty str
      EODHD_API_TOKEN: ${{ secrets.EODHD_API_TOKEN || '' }}
      # Add additional token options here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Validate Python version match
        run: ./scripts/validate_python_version.sh

      - name: Install project dependencies
        run: just install-dev

      - name: Run format + type checks no fixes
        run: just lint-ci

      - name: Run tests
        run: just test

  docker:
    name: Build Docker Images
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install just
        run: |
          curl -sL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Generate .env from .python-version
        run: just docker-build
