name: Release                              # Workflow name shown in the GitHub Actions UI

'on':                                        # Events that trigger this workflow
  push:                                    # Trigger when code is pushed
    branches: [main]                       # …specifically to the main branch
  workflow_dispatch: {}                    # Allow manual runs from the Actions tab

permissions:                               # Permissions granted to the GITHUB_TOKEN
  contents: write                          # Needed to create tags/releases and update files
  pull-requests: write                      # Needed to open or update pull requests
  issues: write                             # Needed if the release process wants to comment on issues

jobs:                                      # List of jobs for this workflow
  release-please:                           # Single job named "release-please"
    runs-on: ubuntu-latest                  # Use the latest Ubuntu runner for execution
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}  # "true"/"false" if new release created
      tag_name: ${{ steps.release.outputs.tag_name }}  # Release tag (e.g., v1.2.3) if release_created "true"
    steps:                                  # Steps to perform in this job
      - uses: googleapis/release-please-action@v4   # GitHub Action that automates versioning and changelogs
        id: release
        with:
          release-type: simple              # No 'token' input—defaults to GITHUB_TOKEN
  cd:
    needs: release-please                   # Wait for job "release-please" to finish and expose its outputs
    if: ${{ needs.release-please.outputs.release_created == 'true' }}  # Run only if new release created
    uses: ./.github/workflows/cd.yml        # Call the reusable workflow at .github/workflows/cd.yml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}  # Pass ver tag to the called workflow's inputs
